env:
  DISPLAY: :99.0
task:
  matrix:
    - name: Chromium (node10 + linux)
      container:
        dockerfile: .ci/Dockerfile.linux
      xvfb_start_background_script: Xvfb :99 -ac -screen 0 1024x768x24
  install_script: npm install --unsafe-perm
  build_script: npm run build
  lint_script: npm run lint
  test_script: npm run test
  
